apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-x18b
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-x18b
    app.kubernetes.io/part-of: tkrw-pr712-0075-0011-app
  name: devfile-sample-x18b
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-x18b
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-x18b
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0011-tenant/tkrw-pr712-0075-0011-app/devfile-sample-x18b@sha256:6b3f44d5250adf8e761a7229e2c2cfde317fe54c49f6c81be7134d4f5ce21918
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
